FROM node:latest

# create root application folder
WORKDIR /app

# copy configs to /app folder
COPY package*.json ./
COPY tsconfig.json ./
# copy source code to /app/src folder
COPY src /app/src

# copy public
COPY public /app/public

# check files list
RUN ls -a

RUN npm install

EXPOSE 8081

CMD [ "npm", "run", "webclient" ]
